parameters:
#    bbi_abbot_rx.example.class: Bbi\AbbotRx\VisitaBundle\Example

services:
#    bbi_abbot_rx.example:
#        class: %bbi_abbot_rx.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
